# config.yml

backend:
  name: test-repo

media_folder: 'assets/uploads'

collections:
  # Landing pages e.g. Home
  - name: 'landingpages'
    label: 'Landing Pages'
    folder: 'pages'
    create: true
    slug: "{{slug}}"
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'xyzzy' }
      - { label: 'Message', name: 'message', widget: 'string' }